# Generated by Django 3.0.4 on 2020-03-25 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200325_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='totalConfessions',
        ),
        migrations.AlterField(
            model_name='confession',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confessions', to='api.Page'),
        ),
    ]
