# Generated by Django 3.0.4 on 2020-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200325_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='pin',
            field=models.PositiveSmallIntegerField(default=1111, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confession',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='pageId',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
