# Generated by Django 3.0.4 on 2020-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200325_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='confId',
            field=models.PositiveIntegerField(default=1234561234, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
