# Generated by Django 3.0.4 on 2020-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200326_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
