# Generated by Django 3.0.4 on 2020-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200326_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
