# Generated by Django 3.0.4 on 2020-03-25 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confessions',
            new_name='Confession',
        ),
    ]
