# Generated by Django 3.0.4 on 2020-03-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200325_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='confId',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='page',
            name='pageId',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
