# Generated by Django 3.0.4 on 2020-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200326_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='ownerLiked',
            field=models.BooleanField(default=False),
        ),
    ]
